### ISSUE TITLE
FYI: Uso legale di questo software

### ISSUE THREAD

**Issue by Enrico204** [GGraziadei/Verifica-C-19-Desktop#1]
Ciao!

Secondo la normativa richiesta dal Garante, l'unico software in grado di poter fare la verifica dei green pass legalmente è la app sviluppata dal Ministero: https://github.com/ministero-salute/it-dgc-verificaC19-android/issues/130

Sebbene non sia illegale implementare questo software, io scriverei un avviso bello evidente nel README per indicare che l'uso di questo software non è consentito per la verifica del green pass, e chi lo usa si assume la responsabilità di farsi autorizzare dagli enti competenti.

**Comment by GGraziadei** [comment]
Corretto, inserirò questo avviso nel breve

Il giorno ven 24 set 2021 alle ore 11:20 Enrico ***@***.***>
ha scritto:
